modLoader="javafml"
loaderVersion="[43,)"
license="GNU_GPL.3"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="tba_diet"
version="${file.jarVersion}"
displayName="Turtle Block Academy Datapack for Diet Mod"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="pack.png"
authors="Warren Tode"
description='''
Just a datapack builder for the Diet mod
'''
[[dependencies.tba_diet]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tba_diet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
