package com.github.warrentode.tba_diet.datagen;

import com.github.warrentode.tba_diet.PackTags;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.tags.BlockTagsProvider;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.Objects;

public class ItemTagsGen extends ItemTagsProvider {
    public ItemTagsGen(DataGenerator generator, BlockTagsProvider blockTagsProvider, String modid, @Nullable ExistingFileHelper helper) {
        super(generator, blockTagsProvider, modid, helper);
    }

    @Override
    protected void addTags() {
        this.registerPackTags();
    }

    private void registerPackTags() {
        tag(PackTags.Items.DIET_SPECIAL_FOOD)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:salmonberry_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:shepherds_pie_block")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersrespite:rose_hip_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersrespite:coffee_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:ichor_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:sky_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:magma_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:ender_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:earth_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:blood_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("supplementaries:pancake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:honey_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:chocolate_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_fruit_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:egg_pie")));

        tag(PackTags.Items.DIET_FRUITS)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:enchanted_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:blueberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("domesticationinnovation:rotten_apple")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:christmas_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:festive_chiken")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:rotten_apple")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_meat_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:steamed_dragon_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_leg_with_sauce")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:grilled_shulker")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:swet_syrup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:aether_flower_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:glazed_apple")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_juice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:jeweled_apple")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("phantasm:oblifruit")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("phantasm:pream_berry")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("phantasm:chorus_fruit_salad")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:nether_skewer")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:magma_gelatin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:pumpkin_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:pumpkin_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:pasta_with_veggieballs")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:sweet_berry_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:sweet_berry_ice_cream")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:sweet_berry_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:succotash")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:sugar_cane")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:stuffed_rice_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:stir_fried_shulker_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_flower_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:ender_sauce")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:mixed_salad")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:end_barbecue_stick")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_breath_and_chorus_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_fruit_popsicle")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_fruit_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_fruit_milk_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:bubble_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:assorted_salad")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:prickly_pear")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:cooked_prickly_pear")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_sweet_berry_kriek")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_pumpkin_kvass")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_apple_lambic")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("create:honeyed_apple")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("create:chocolate_glazed_berries")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:shrimp_skewer")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:swet_pudding")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:bowl_of_enchanted_berries")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:bowl_of_blue_berries")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:grim_apple")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_fruit_grain")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:cantaloupe_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:cantaloupe")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:enchanted_berry")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:blue_berry")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:propelpearl")))
                .add(Items.PUMPKIN)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:tomato")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("xercamod:tomato")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberries")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberries")));

        tag(PackTags.Items.DIET_VEGETABLES)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:plate_of_stuffed_hoglin_snout")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:plate_of_stuffed_hoglin_ham")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:plate_of_stuffed_hoglin_roast")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:brown_mushroom_colony")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:red_mushroom_colony")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:warped_fungus_colony")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:crimson_fungus_colony")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("domesticationinnovation:sinister_carrot")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:kelp_shake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_meat_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:steamed_dragon_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_leg_with_sauce")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:aether_flower_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:warped_wart")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:wandering_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:flowering_purpur_grass")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_roots")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_pie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:seagrass_salad")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:honey_fried_kelp")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:cooked_stuffed_cod")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:stuffed_cod")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:cabbage_wrapped_elder_guardian")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:braised_sea_pickle")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:warped_moldy_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:strider_moss_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:mimicarnation")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:grilled_strider")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:pumpkin_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:pumpkin_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:vegetable_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:vegetable_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:fish_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:fish_stew_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:chicken_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:chicken_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:beef_stew_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:baked_cod_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:baked_cod_stew_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:rabbit_stew_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:mushroom_stew_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:beetroot_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:bowl_of_stuffed_squid")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:pasta_with_veggieballs")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:cave_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:cave_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:improvised_barbecue_stick")))
                .add(Items.LARGE_FERN)
                .add(Items.FERN)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:baked_cave_carrot")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:succotash")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:corn_bread")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:salmon_verrines")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:longevity_noodle")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:stir_fried_shulker_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:grilled_shulker")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:ender_sauce")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:mixed_salad")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:assorted_salad")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:tropical_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_pumpkin_kvass")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:surf_and_turf")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:stuffed_nautilus_shell")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:shrimp_skewer")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:crab_cakes")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:clam_chowder")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:clam_bake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:bisque")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:aechor_petal")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("friendsandfoes:buttercup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:coconut_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:coconut_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:azalea_flower")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:cactus_flesh")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:pink_hibiscus")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:yellow_autumn_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:wilted_lily")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:willow_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:wildflower")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:white_cherry_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:violet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:umbran_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:toadstool")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:tall_lavender")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:rose")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:redwood_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:rainbow_birch_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:pink_hibiscus")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:pink_daffodil")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:pink_cherry_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:palm_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:origin_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:orange_cosmos")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:orange_autumn_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:maple_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:mahogany_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:magic_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:lavender")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:jacaranda_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:icy_iris")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:hellbark_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:goldenrod")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:glow_shroom")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:glowflower")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:flowering_oak_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:fir_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:dead_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:burning_blossom")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:blue_hydrangea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:skyroot_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:white_flower")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:purple_flower")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:golden_oak_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:holiday_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:decorated_holiday_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:crystal_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:crystal_fruit_leaves")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:chopped_clover")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:corn")))
                .add(Items.CACTUS)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:prickly_pear")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:cooked_prickly_pear")))
                .add(Items.PUMPKIN)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_succulent")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dried_chorus_flower")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_petal")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:warped_wart")))
                .add(Items.CRIMSON_ROOTS)
                .add(Items.WARPED_ROOTS)
                .add(Items.NETHER_WART)
                .add(Items.SEA_PICKLE)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:cabbage")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:wild_onion")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:onion")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:tomato")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("xercamod:tomato")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:cave_carrot")))
                .add(Items.RED_MUSHROOM)
                .add(Items.BROWN_MUSHROOM)
                .add(Items.CRIMSON_FUNGUS)
                .add(Items.WARPED_FUNGUS)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("phantasm:putac_brochette")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("phantasm:putac_shroom")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:chorus_fungus")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:crimson_fungus_colony")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:warped_fungus_colony")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:red_mushroom_colony")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:brown_mushroom_colony")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:glowshroom")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:toadstool")));

        tag(PackTags.Items.DIET_GRAINS)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:enchanted_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:blueberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:festive_chiken")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:gingerbread_man")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:bowl_of_ginger_cookies")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("snowyspirit:gingerbread_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("snowyspirit:gingerbread")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:elder_guardian_roll")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:fugu_roll")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:noodle_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:noodle_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:bowl_of_stuffed_squid")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:pasta_with_veggieballs")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_honey_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_chocolate_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:honey_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:golden_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cookie_of_unbinding")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:chocolate_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:succotash")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:popcorn")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:corn_bread")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:longevity_noodle")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:stuffed_rice_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_muffin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_fruit_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:egg_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:egg_in_basket")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:bread_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:tropical_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_sweet_berry_kriek")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_pumpkin_kvass")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_night_howl_kvass")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_haars_icey_pale_lager")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_blaze_stout")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_blaze_milk_stout")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_apple_lambic")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("createaddition:honey_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("createaddition:chocolate_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("create:sweet_roll")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:seafood_gumbo")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:crab_cakes")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:bisque")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:swet_pudding")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:festive_sweets")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("create:wheat_flour")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("create:dough")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:corn")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:kernels")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:popcorn")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:rice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("xercamod:rice")));

        tag(PackTags.Items.DIET_PROTEINS)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:grilled_shulker")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("unusualend:ender_firefly_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:cooked_aerfilet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:raw_aerfilet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:ground_strider")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:strider_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:hoglin_sirloin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:hoglin_loin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:hoglin_ear")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:plate_of_stuffed_hoglin_snout")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:plate_of_stuffed_hoglin_ham")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:plate_of_stuffed_hoglin_roast")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:golden_gummy_swet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:blue_gummy_swet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:festive_chiken")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_meat_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:steamed_dragon_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_leg_with_sauce")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:smoked_ham_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:salmon_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:mutton_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:cod_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:chicken_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:beef_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:bacon_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:scrambled_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:sliced_boiled_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:peeled_boiled_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:boiled_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:swet_syrup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:sky_slime_ball")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:ichor_slime_ball")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:ender_slime_ball")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("snowyspirit:eggnog")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:tentacle_on_a_stick")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:stuffed_cod")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:squid_rings")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:cabbage_wrapped_elder_guardian")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:braised_sea_pickle")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:warped_moldy_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:strider_moss_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:nether_skewer")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:magma_gelatin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:grilled_strider")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:pumpkin_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:pumpkin_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:vegetable_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:vegetable_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:hot_cocoa")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:hot_cocoa_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:fish_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:fish_stew_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:chicken_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:chicken_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:beef_stew_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:noodle_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:noodle_soup_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:baked_cod_stew_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:rabbit_stew_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:bowl_of_stuffed_squid")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:improvised_barbecue_stick")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:milk_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:white_chocolate_bar")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:sweet_berry_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_honey_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_chocolate_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:napolitano_ice_cream")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:napolitano_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:mocha_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:mocha_ice_cream")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:milk_chocolate_bar")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:glow_berry_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cream_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cookie_of_unbinding")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:coffee_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:chocolate_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:brigadeiro_mix")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:brigadeiro")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:beijinho")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:succotash")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:salmon_verrines")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:longevity_noodle")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:stir_fried_shulker_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:fried_dragon_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:liquid_dragon_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:non_hatchable_dragon_egg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:ender_pearl_grain")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dried_endermite_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:raw_ender_mite_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:end_barbecue_stick")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_breath_and_chorus_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_fruit_milk_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:bubble_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:egg_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:egg_in_basket")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:bacon_and_egg_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_night_howl_kvass")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:surf_and_turf")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:stuffed_nautilus_shell")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:shrimp_skewer")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:seafood_gumbo")))
                .add(Items.TROPICAL_FISH)
                .add(Items.PUFFERFISH)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:crab_cakes")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:clam_chowder")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:clam_bake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:bisque")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:swet_pudding")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:sweet_and_sour_soup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:aechor_petal")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:bat_wing")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:smoked_bat_wing")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:silverfish_eggs")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:weird_caviar")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:squid")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:glow_squid")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:baked_squid")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cream_cheese")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_leg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:smoked_dragon_leg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:raw_dragon_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:raw_dragon_meat_cuts")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:roasted_dragon_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:roasted_dragon_steak")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:roasted_dragon_meat_cuts")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_breath_soda")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:roasted_shulker_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:shulker_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:shulker_meat_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("artifacts:eternal_steak")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("artifacts:everlasting_beef")))
                .add(Items.MILK_BUCKET)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:milk_bottle")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:condensed_milk")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:skyroot_milk_bucket")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:cut_tentacles")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:tentacles")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:tentacles")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:baked_tentacles")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:glow_squid")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:cut_tentacles")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:tentacles")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:tentacles")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:squid")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:walnut")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:crab_claw")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:crab_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ecologics:tropical_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:crab")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:cooked_crab")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:crab_legs")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:fish_stick")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:pufferfish_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:cooked_pufferfish_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:tropical_fish_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:cooked_tropical_fish_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:cooked_tropical_fish")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:raw_clam_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:clam_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:shrimp")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:cooked_shrimp")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:clawster")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:cooked_clawster")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:mutton_chops")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:minced_beef")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:bacon")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:bacon")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:raw_goat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:venison_chops")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:guardian_tail")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:cooked_stuffed_cod")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:guardian")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:elder_guardian_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:elder_guardian_roll")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:fugu_roll")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:fugu_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:elder_guardian_slab")));

        tag(PackTags.Items.DIET_SUGARS)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:golden_gummy_swet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:blue_gummy_swet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:gingerbread_man")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:kelp_shake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:christmas_tea")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:festive_chiken")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aether:candy_cane")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("snowyspirit:gingerbread_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("snowyspirit:candy_cane")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("oceansdelight:honey_fried_kelp")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:hot_cocoa")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("miners_delight:hot_cocoa_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:white_chocolate_bar")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:sweet_berry_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_honey_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_chocolate_cheese_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:piece_of_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:mocha_coffee")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:milk_chocolate_bar")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:macchiato_coffee")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:latte_coffee")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:honey_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:golden_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:glow_berry_ice_cream")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:glow_berry_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:expresso_coffee")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:dark_chocolate_bar")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cream_ice_cream")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cream_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cookie_of_unbinding")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:coffee_ice_cream")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:coffee_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:chocolate_milkshake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:chocolate_ice_cream")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:chocolate_cookie")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cappuccino_coffee")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:brigadeiro_mix")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:brigadeiro")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:american_coffee")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:candy_corn")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:sugar_cane")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:gingerbread_creeper")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:gingerbread_man")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:gingerbread_cookie_sword")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("festive_delight:gingerbread_cookie_flake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:stuffed_rice_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_breath_soda")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_jam_sandwich")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:cranberry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blackberry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:raspberry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:blueberry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:glow_berry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("wildberries:sweet_berry_jam")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:chorus_fruit_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:egg_pie_slice")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("drinkbeer:beer_mug_blaze_milk_stout")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("createaddition:honey_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("createaddition:chocolate_cake")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("create:sweet_roll")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("create:honeyed_apple")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("create:chocolate_glazed_berries")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("create:bar_of_chocolate")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("aetherdelight:festive_sweets")))
                .add(Items.SUGAR)
                .add(Items.HONEY_BOTTLE);

        tag(PackTags.Items.DIET_FATS)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:hoglin_sirloin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:hoglin_loin")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:hoglin_ear")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:plate_of_stuffed_hoglin_snout")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:plate_of_stuffed_hoglin_ham")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("nethersdelight:plate_of_stuffed_hoglin_roast")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("fastfooddelight:fried_onions")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("fastfooddelight:carrot_fries")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("fastfooddelight:french_fries")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_meat_stew")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_leg_with_sauce")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:smoked_ham_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:mutton_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:beef_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:bacon_omelet")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("hauntedharvest:succotash")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:roasted_dragon_steak")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:roasted_dragon_meat_cuts")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:raw_dragon_meat_cuts")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:raw_dragon_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:roasted_dragon_meat")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:dragon_leg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("ends_delight:smoked_dragon_leg")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("eggdelight:bacon_and_egg_cup")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:surf_and_turf")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("crabbersdelight:seafood_gumbo")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("kawaiidishes:cream_cheese")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("artifacts:eternal_steak")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("artifacts:everlasting_beef")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:goat")))
                .add(Items.MUTTON)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:mutton_chops")))
                .add(Items.BEEF)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:minced_beef")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("tconstruct:bacon")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:bacon")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:goat")))
                .add(Items.PORKCHOP)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("farmersdelight:ham")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("simplefarming:olive_oil")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("vanillafoodpantry:seedoil_jar")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("vanillafoodpantry:sunbutter_jar")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("vanillafoodpantry:portion_butter")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("pamhc2foodcore:mayonaiseitem")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("pamhc2foodcore:sesameoilitem")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("pamhc2foodcore:mushroomoilitem")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("pamhc2foodcore:cookingoilitem")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("pamhc2foodcore:butteritem")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("croptopia:butter")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("croptopia:olive_oil")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:animal_oil_bottle")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("delightful:animal_fat")));
    }
}
